### PR TITLE
MCS-1971 - Incorporate new scorecard values for eval 7 

### PR DESCRIPTION
**Pull request by rartiss55**
See ingest PR here: 
https://github.com/NextCenturyCorporation/mcs-ingest/pull/140

On the Test Overview page, I put the values next to the other tool use ones as opposed to adding them to the end of the list, in case anyone has trouble finding them.

### CODE REVIEW

**Comment by ThomasSchellenbergNextCentury** [comment]
@phile-caci Maybe a stupid question, but you made sure to ingest the scene history file using Rachel's corresponding `mcs-ingest` feature branch, right?

I'll try to test this thing out myself later tonight.

**Comment by phile-caci** [comment]
> @phile-caci Maybe a stupid question, but you made sure to ingest the scene history file using Rachel's corresponding `mcs-ingest` feature branch, right?
> 
> I'll try to test this thing out myself later tonight.

I'm pretty sure I did, the Hooked Tool Rotation info came through.

**Comment by ThomasSchellenbergNextCentury** [comment]
Ugh... I must have messed something up... I keep getting graphql Bad Request errors when trying to view Multi Tool Use in Test Overview or Scene Analysis... I guess I'll try this again on Monday.

**Comment by phile-caci** [comment]
> > > @phile-caci Maybe a stupid question, but you made sure to ingest the scene history file using Rachel's corresponding `mcs-ingest` feature branch, right?
> > > I'll try to test this thing out myself later tonight.
> > 
> > 
> > I'm pretty sure I did, the Hooked Tool Rotation info came through.
> 
> @phile-caci I looked through the history file posted -- even though I see a rotation in the video, I didn't see a successful rotate action on the straight tool in the history file (just successful moves). Did you post the right one?

hmm maybe I didn't even ingest the right one...  I will redo to be sure

**Comment by ThomasSchellenbergNextCentury** [comment]
Update: Rachel noted that I was using "Evaluation 6" instead of "Evaluation 7"; however, using "Evaluation 7" didn't fix my problem.

HOWEVER, I just tried ingesting Phi's scene and history files, and they work fine... So something must be weird with the scene and/or history files I generated. I'll do some digging.

**Comment by ThomasSchellenbergNextCentury** [comment]
[thomas_multitooluse.zip](https://github.com/NextCenturyCorporation/mcs-ui/files/13072965/thomas_multitooluse.zip)

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]
It was the lack of a "team" in my history file that was causing the error... Thanks Rachel.

Approved!

**Review by phile-caci — APPROVED** [review]
Retested with just a hooked tool rotation scene to make sure the score shows the right number (I 
 probably ingested the wrong scene)  Thanks!

**Pull request merged**
